function [v1] = v1_new(s, x, y, r, t_j, x1_j, x2_j, p0, p1, p2, p3, N, eta1, eta2, eta3, a1, a2, b1, b2, lambda_, ampl)
    t_new  = (s  - t_j)/r;
    x1_new = (x - x1_j)/r;
    x2_new = (y - x2_j)/r;


    fact=ampl*0.5*(a1*b2-a2*b1); % multiply by r

    v1 = fact*lambda_*cutoff(sign(t_new)*t_new).*(...
            dxxy_psi(N, eta1, eta2, eta3, x1_new, x2_new, t_new)*cutoff(sqrt(x1_new^2 + x2_new^2)) ...
        +   dxx_psi( N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dy_phi(  x1_new, x2_new) ...
        + 2*dxy_psi( N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dx_phi(  x1_new, x2_new) ...
        + 2*dx_psi(  N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dxy_phi( x1_new, x2_new) ...
        +   dy_psi(  N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dxx_phi( x1_new, x2_new) ...
        +   fpsi(    N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dxxy_phi(x1_new, x2_new) ...
        + 3*dyy_psi( N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dy_phi(  x1_new, x2_new) ...
        + 3*dy_psi(  N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dyy_phi( x1_new, x2_new) ... 
        +   fpsi(    N, eta1, eta2, eta3, x1_new, x2_new, t_new).*dyyy_phi(x1_new, x2_new) ...
        + dyyy_psi(  N, eta1, eta2, eta3, x1_new, x2_new, t_new).*cutoff(sqrt(x1_new^2 + x2_new^2)));
    
    
